# Generated by Django 4.2.1 on 2023-06-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('quantidade', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('ibu', models.PositiveIntegerField()),
                ('abv', models.FloatField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem', models.ImageField(upload_to='images')),
            ],
        ),
    ]
