# Generated by Django 4.2.1 on 2023-06-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_produto_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quantidade',
            new_name='conteudo',
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=45),
        ),
    ]
