# Generated by Django 4.2.1 on 2023-06-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_quantidade_produto_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pedido',
            field=models.CharField(default='ABCDE123', max_length=8),
        ),
    ]
