# Generated by Django 4.2.1 on 2023-06-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_produto_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qtde',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
