# Generated by Django 4.2.1 on 2023-06-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_produto_qtde_produto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pedido',
            field=models.CharField(default='ABCD1234', max_length=8),
        ),
    ]
