# Generated by Django 4.2.1 on 2023-06-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_produto_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pedido',
            field=models.CharField(blank=True, default='ABCD1234', max_length=8),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtde',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
