# Generated by Django 4.2.1 on 2023-06-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_produto_pedido_alter_produto_qtde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pedido',
            field=models.CharField(default='ABCD0123', max_length=8),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtde',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
