# Generated by Django 4.2.2 on 2023-08-06 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_produto_pedido_alter_produto_qtde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.marca'),
        ),
    ]
